# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "blog"
email: chris@brookins.info
description: > # this means to ignore newlines until "baseurl:"
  > my place on the internet
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://tech.brookins.info" # the base hostname & protocol for your site
twitter_username:
github_username:  cbrookins
mastodon_username: cbrookins@mastodon.social
mastodon_url: https://mastodon.social/@cbrookins
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  style: compressed

include: [ "/.well-known" ]

images: '/assets/images'
